name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-image:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup mkosi
        uses: systemd/mkosi@c37a55f91bc4b5fe325123e971b10ab0d0e8a0f6
      - name: Initialize secure boot secrets
        if: github.repository == 'davide125/arcadeos'
        env:
          ARCADEOS_SECURE_BOOT_CERTIFICATE: ${{vars.ARCADEOS_SECURE_BOOT_CERTIFICATE}}
          ARCADEOS_SECURE_BOOT_KEY: ${{secrets.ARCADEOS_SECURE_BOOT_KEY}}
        run: |
          echo "$ARCADEOS_SECURE_BOOT_CERTIFICATE" > mkosi.crt
          echo "$ARCADEOS_SECURE_BOOT_KEY" > mkosi.key
          chmod 0600 mkosi.key
      - name: Bootstrap
        run:  ./scripts/bootstrap
      # https://github.com/systemd/mkosi/commit/57ebda7c5fa47a4dd3df829d776a10c23e8cdb4a
      - name: Build tools tree
        run: ./mkosi -f box -- true
      - name: Free disk space
        uses: sudo rm -rf /usr/local/lib/android /usr/share/dotnet
      - name: Build
        run:  ./mkosi -f
